#!/bin/zsh
set -eu

# DIASPORA-CONSUMER

if (( ${#*} != 3 )) {
  print "consumer: Provide ROOT_PATH TOPIC FIFO"
  print "          Ensure the FIFO is already open for reading"
  print "                 by some process."
  return 1
}

ROOT_PATH=$1
TOPIC=$2
FIFO=$3

echo "$FIFO <- $TOPIC" > $ROOT_PATH/ctl.fifo
