#!/bin/zsh
set -eu

# DIASPORA-FIFO
# Make the Diaspora CTL FIFO

if (( ${#*} != 1 )) {
  print "diaspora-fifo: Provide ROOT_PATH"
  return 1
}

ROOT_PATH=$1
FIFO=$ROOT_PATH/ctl.fifo

mkdir -pv $ROOT_PATH
touch $FIFO

print "diaspora-fifo: control FIFO is at $FIFO"

diaspora-ctl fifo --driver files                     \
                  --driver.root_path $ROOT_PATH      \
                  --control-file     $FIFO           &
PID=${$}

print "diaspora-fifo: FIFO is PID $PID"

wait
